export { default as DetailView } from './DetailView'
export { default as LoginView } from './LoginView'
export { default as MenuView } from './MenuView'
export { default as AccountView } from './AccountView'
export { default as RestaurantsView } from './RestaurantsView'
export { default as SignUpView } from './SignUpView'
